name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: read

env:
  GOPRIVATE: github.com/Layr-Labs/*

jobs:
  Test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24.x'
          
      - name: Configure git for private repos
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run Tests
        run: |
          go mod tidy
          make tests
